// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWSzzyzDxanhv0BhgzAog_tf8J1HRWVdM',
    appId: '1:669532145079:web:0d9a7e464aa1f464799432',
    messagingSenderId: '669532145079',
    projectId: 'test-minitok',
    authDomain: 'test-minitok.firebaseapp.com',
    storageBucket: 'test-minitok.firebasestorage.app',
    measurementId: 'G-SZ7BJKM3CC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsVE85BeV-rdC30x3oJ4eJkqZeraWTYEw',
    appId: '1:669532145079:android:4105657a7b26fcd6799432',
    messagingSenderId: '669532145079',
    projectId: 'test-minitok',
    storageBucket: 'test-minitok.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGm78D1zcBmNc8G8gsNzVtn1bdkn7YJlI',
    appId: '1:669532145079:ios:44217447dd95ccbd799432',
    messagingSenderId: '669532145079',
    projectId: 'test-minitok',
    storageBucket: 'test-minitok.firebasestorage.app',
    iosBundleId: 'com.example.minitok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGm78D1zcBmNc8G8gsNzVtn1bdkn7YJlI',
    appId: '1:669532145079:ios:44217447dd95ccbd799432',
    messagingSenderId: '669532145079',
    projectId: 'test-minitok',
    storageBucket: 'test-minitok.firebasestorage.app',
    iosBundleId: 'com.example.minitok',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWSzzyzDxanhv0BhgzAog_tf8J1HRWVdM',
    appId: '1:669532145079:web:2db1e46d0344ee88799432',
    messagingSenderId: '669532145079',
    projectId: 'test-minitok',
    authDomain: 'test-minitok.firebaseapp.com',
    storageBucket: 'test-minitok.firebasestorage.app',
    measurementId: 'G-CKPTZCG0FK',
  );
}
